# Generated by Django 3.2.3 on 2021-05-26 15:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_movie',
            field=models.ManyToManyField(related_name='vote_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
